update Mongo & Mongoose to support Mongo version 6
PaystackHQ/paystack-music-api pull request #106
Opened 2024-09-10 16:42 UTC by Andrew-Paystack

2024-09-10 16:49 UTC, Andrew-Paystack commented
Hey @tolu-paystack ,

Please review my p/r that updates the Mongo DB version in use 🙏

2024-09-11 09:26 UTC, tolu-paystack commented
@Andrew-Paystack I see you've updated the mongoose version and added the Node.js mongodb driver as well. There's no need to add the driver, as mongoose uses it internally.

To be clear, it's the MongoDB **Server** version that's being updated to v6.0. That's totally separate from the driver, which you added here.

You might also want to confirm that the [mongoose.connect](https://github.com/PaystackHQ/paystack-music-api/blob/228760dea6d6d871815dcd10f41163a0b9600ba4/config/db.js#L6) code works as expected, as I see that [one of the breaking changes](https://mongoosejs.com/docs/migrating_to_6.html#mongoose-connect-returns-a-promise) going from v5 to v6 was that it now returns a promise instead of an instance.

2024-09-18 10:43 UTC, Andrew-Paystack commented
Hey @tolu-paystack , 

Made the changes and successfully tested.

2024-09-18 11:09 UTC, tolu-paystack requested changes

2024-09-18 11:09 UTC, tolu-paystack commented on config/db.js
> +const conn = async () => mongoose.connect(databaseURI);
You're missing an `await` here @Andrew-Paystack

2024-09-18 11:09 UTC, tolu-paystack commented on config/db.js
> +const conn = async () => mongoose.connect(databaseURI);
I think you should also consider putting this in a try catch block, in case there are errors when attempting to connect to the DB

2024-09-18 11:09 UTC, tolu-paystack commented on config/db.js
> +module.exports = conn();
You're calling the function in your export here @Andrew-Paystack, rather than passing the function to be used elsewhere

2024-09-19 14:36 UTC, Andrew-Paystack commented
@tolu-paystack Made the changes 🙏

2024-09-20 10:28 UTC, tolu-paystack approved these changes
LGTM

2024-09-20 10:28 UTC, merged